steps:
  build-and-push:
    image: plugins/docker
    settings:
      repo: ${CI_REPO_OWNER%%io}/${CI_REPO_NAME%%-service}
      tags: latest
      platforms: linux/amd64, linux/arm64
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
when:
  - event: push
    branch: [master, main]
