steps:
  release:
    image: plugins/docker
    settings:
      repo: ${CI_REPO_OWNER%%io}/${CI_REPO_NAME%%-service}
      tags: ${CI_COMMIT_TAG##v}
      platforms: linux/amd64, linux/arm64
      docker_username:
        from_secret: docker_username
      docker_password:
        from_secret: docker_password
when:
  - event: tag
    ref: refs/tags/v*
